//
// Created by Michael on 10.11.2024.
//

#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

#define MAX_NAME_LENGTH 32
#define STALEMATE_VALUE 0
#define FIRST_PLAYER_WON 1
#define SECOND_PLAYER_WON -1
#define ROCK_VALUE 1
#define SCISSORS_VALUE 2
#define PAPER_VALUE 3
#define LIZARD_VALUE 4
#define SPOCK_VALUE 5
#define FAILURE_VALUE -10
#define MAX_NUMBER_OF_PLAYERS 10
#define FREE_POSITION -1
#define IN_LOBBY_VALUE 1
#define WAITING_VALUE 2
#define IN_GAME_VALUE 3
#define MESSAGE_NOT_VALID -1
#define START_OF_MESSAGE 5
#define LENGTH_OF_MESSAGE_SIGNATURE 4
#define MAXIMAL_LENGHT_OF_MESSAGE_TYPE 10
#define TURN_NOT_PICKED_YET -1
#define NOONE_PLAYED_YET -1
#define SUCCESS_VALUE 1
#define MAX_SIZE_OF_MESSAGE 1024
#define PORT 10000
#define STRINGS_ARE_SAME 0
#define LENGHT_OF_START_GAME_MESSAGE 16
#define LENGTH_OF_BOTHPLAYERS_TURED_MESSAGE 26
#define LOGOUT_VALUE -30
#define LOGIN_VALUE -11
#define TURN_VALUE -12
#define GAME_VALUE -4
#define PING_VALUE -5
#define NAME_ALREADY_USED -2
#define TRYING_TO_RECONNECT_VALUE -12
#define NEUTRAL_VALUE -20
#define CEKAM_NA_SIGNAL -77
#define TIME_FOR_ONE_PING 1200
#define TIME_FOR_MORE_PINGS 50050
#define MORE_PINGS 10
#define ROUNDS 5
#define TYPE_ONE_MESSAGE_LENGTH 33
#define TYPE_TWO_MESSAGE_LENGTH 29
#define TYPE_THREE_MESSAGE_LENGTH 29
#endif //SERVER_CONSTANTS_H
