//
// Created by Michael on 10.11.2024.
//

#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

#define MAX_NAME_LENGTH 32
#define STALEMATE_VALUE 0
#define VICOTRY_VALUE 1
#define DEFEAT_VALUE -1
#define ROCK_VALUE 1
#define PAPER_VALUE 2
#define SCISSORS_VALUE 3
#define LIZARD_VALUE 4
#define SPOCK_VALUE 5
#define FAILURE_VALUE -10
#define MAX_NUMBER_OF_PLAYERS 50
#define FREE_POSITION 0
#define IN_LOBBY_VALUE 1
#define WAITING_VALUE 2
#define IN_GAME_VALUE 3
#define MESSAGE_NOT_VALID -1
#define START_OF_MESSAGE 5
#define LENGTH_OF_MESSAGE_SIGNATURE 4
#define MAXIMAL_LENGHT_OF_MESSAGE_TYPE 10
#define SUCCESS_VALUE 1

#endif //SERVER_CONSTANTS_H
